##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Place standard cells                                   ##
##  -Place core pins                                        ##
##  -Perform initial route of the design                    ##
##############################################################
##Place the design
place_design

opt_design -pre_cts

eval_legacy {setCTSMode -engine ck}
eval_legacy {clockDesign -specFile Clock.ctstch -outDir clk_report}

opt_design -post_cts

report_timing
